version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Ajouter le mot de passe"
    volumes:
      - DevOps_DataBase_Volume:/var/lib/mysql
      - config/config.cnf:/etc/mysql/my.cnf
    
volumes:
   DevOps_DataBase_Volume: