version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Ajouter le mot de passe"
    volumes:
      - DevOps_DataBase_Volume:/var/lib/mysql
      - /root/devops/dev-ops-2019/database/config/config.cnf:/etc/mysql/my.cnf
      - /root/devops/dev-ops-2019/database/config/encryption.cnf:/etc/mysql/conf.d/encryption.cnf
      - /root/devops/dev-ops-2019/database/keys.enc:/etc/mysql/keys.enc
    
volumes:
   DevOps_DataBase_Volume: