version: '2'
services:
  api-server:
    build: ./aubonbeurre-api
    ports:
      - "3009:3009"
    command: node server.js
  vue-server:
    build: ./aubonbeurre-dataviz
    ports:
      - "8080:8080"
    command: npm run serve
  nginx-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "3009:3009"