version: '3.1'
services:
  emailing:
    image: python:rc-alpine3.9
    command: 
  automate1-1:
    build: ./automate
    ports:
      - "9001:9001"
    command: python generator.py 1 9001
  automate1-2:
    build: ./automate
    ports:
      - "9002:9002"
    command: python generator.py 2 9002
  automate1-3:
    build: ./automate
    ports:
      - "9003:9003"
    command: python generator.py 3 9003
  automate1-4:
    build: ./automate
    ports:
      - "9004:9004"
    command: python generator.py 4 9004
  automate1-5:
    build: ./automate
    ports:
      - "9005:9005"
    command: python generator.py 5 9005
  unit1:
    build: ./unit
    volumes:
      - unit1-data:/usr/src/datas
    command: python aggregor.py 1 automate1-1 9001 1 automate1-2 9002 2 automate1-3 9003 3 automate1-4 9004 4 automate1-5 9004 5
    depends_on:
      - emailing
    links: 
        - emailing
  unit1-db:
    build: ./unit
    volumes:
      - unit1-data:/usr/src/datas
    command: 
      - python -m smtpd -c DebuggingServer -n localhost:1025 &
      - python dbStorage.py vps691279.ovh.net docker_concentrator docConPass44 3306
volumes:
  unit1-data: